# Generated by Django 2.1.2 on 2018-10-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='airport',
        ),
        migrations.AddField(
            model_name='journey',
            name='arrival_airport',
            field=models.ForeignKey(default=1200, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='MyApp.Airport'),
        ),
        migrations.AddField(
            model_name='journey',
            name='origin_airport',
            field=models.ForeignKey(default=1100, on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='MyApp.Airport'),
        ),
    ]
