# Generated by Django 2.1.2 on 2018-10-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20181025_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='MyApp.City'),
        ),
    ]
