# Generated by Django 2.1.2 on 2018-10-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20181025_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='MyApp.City'),
        ),
    ]
